spring:
  application:
    name: spring-cloud-eurek

server:
  port: 8000

eureka:
  register-with-eureka: false
  client:
     fetch-registry: false
     serviceUrl:
      defaultZone: http://localhost:8000/eureka/